# Generated by Django 5.2.17 on 2026-09-04 23:08

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                ("mode", models.CharField(default="retrospective", max_length=20)),
                ("config", models.JSONField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("state", models.CharField(db_index=True, default="queued", max_length=20)),
                ("completed_at", models.DateTimeField(null=True)),
                ("result_version", models.CharField(max_length=64, null=True)),
                ("summary", models.JSONField(null=True)),
                ("warnings", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Discovery",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bbox", models.JSONField()),
                ("status", models.CharField(default="queued", max_length=20)),
                ("source_status", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Polygon",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("source", models.CharField(default="user", max_length=40)),
                ("source_ref", models.TextField(blank=True)),
                ("current_version", models.PositiveIntegerField(default=1)),
                ("crop_type", models.CharField(max_length=100, null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SourceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=60)),
                ("query_hash", models.CharField(db_index=True, max_length=64)),
                ("geometry_hash", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(max_length=20)),
                ("artifact_path", models.TextField()),
                ("checksum", models.CharField(max_length=64)),
                ("metadata", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnomalyPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("severity", models.CharField(max_length=20)),
                ("data", models.JSONField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="core.analysisrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CandidatePolygon",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("geometry", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("area_ha", models.FloatField()),
                ("source_ref", models.TextField()),
                ("name", models.CharField(max_length=200, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "discovery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="core.discovery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("format", models.CharField(max_length=10)),
                ("state", models.CharField(default="queued", max_length=20)),
                ("artifact_path", models.TextField(blank=True)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateTimeField()),
                (
                    "run",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.analysisrun"),
                ),
                (
                    "workspace",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.workspace"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_id", models.CharField(max_length=64, unique=True)),
                ("artifact_hash", models.CharField(max_length=64)),
                ("manifest_path", models.TextField()),
                ("manifest", models.JSONField()),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)), fields=("active",), name="one_active_model"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="model_version",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.modelversion"),
        ),
        migrations.CreateModel(
            name="CropSeason",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("season_start", models.DateField()),
                ("season_end", models.DateField()),
                ("crop_type", models.CharField(max_length=100, null=True)),
                ("origin", models.CharField(default="user", max_length=20)),
                (
                    "polygon",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.polygon"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PolygonVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("geometry", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("geometry_hash", models.CharField(db_index=True, max_length=64)),
                ("area_ha", models.FloatField()),
                (
                    "polygon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.polygon",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="polygon_version",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.polygonversion"),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("provider", models.CharField(default="nominatim", max_length=40)),
                ("external_id", models.CharField(max_length=100)),
                ("bbox", models.JSONField()),
                ("geometry", django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "external_id"), name="unique_region_source")
                ],
            },
        ),
        migrations.AddField(
            model_name="polygon",
            name="region",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.region"
            ),
        ),
        migrations.AddField(
            model_name="discovery",
            name="region",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.region"),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="snapshots",
            field=models.ManyToManyField(to="core.sourcesnapshot"),
        ),
        migrations.AddField(
            model_name="polygon",
            name="workspace",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.workspace"),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=20)),
                ("state", models.CharField(db_index=True, default="queued", max_length=20)),
                ("stage", models.CharField(default="validating", max_length=40)),
                ("progress", models.FloatField(null=True)),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("heartbeat_at", models.DateTimeField(null=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("dispatched_at", models.DateTimeField(null=True)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("retryable", models.BooleanField(default=False)),
                ("error", models.JSONField(null=True)),
                (
                    "discovery",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.discovery",
                    ),
                ),
                (
                    "export",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.export",
                    ),
                ),
                (
                    "parent_job",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.job"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.analysisrun",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.workspace"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("response", models.JSONField()),
                (
                    "workspace",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.workspace"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="discovery",
            name="workspace",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.workspace"),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="workspace",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.workspace"),
        ),
        migrations.CreateModel(
            name="DailyEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("data", models.JSONField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="core.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [models.UniqueConstraint(fields=("run", "date"), name="unique_run_date")],
            },
        ),
        migrations.AddConstraint(
            model_name="polygonversion",
            constraint=models.UniqueConstraint(fields=("polygon", "version"), name="unique_polygon_version"),
        ),
        migrations.AddIndex(
            model_name="polygon",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["workspace", "-created_at"],
                name="active_workspace_polygons",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("workspace", "key"), name="unique_workspace_idempotency"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(fields=["workspace", "-created_at"], name="core_analys_workspa_b78d44_idx"),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["queued", "running"])),
                fields=("workspace", "fingerprint"),
                name="one_active_analysis",
            ),
        ),
    ]
