# Generated by Django 5.2.17 on 2026-09-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="manifest_checksum",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="cropseason",
            constraint=models.CheckConstraint(
                condition=models.Q(("season_end__gte", models.F("season_start"))),
                name="crop_season_date_order",
            ),
        ),
    ]
